export const HightLights = [
    {
        id: "church01",
        name: "church01",
        class: "church",
        coverPhoto: "/images/works/church-01/1.jpg",
    },
    {
        id: "consumer01",
        name: "consumer01",
        class: "consumer",
        coverPhoto: "/images/works/consumer-01/1.jpg",
    },
    {
        id: "consumer02",
        name: "consumer02",
        class: "consumer",
        coverPhoto: "/images/works/consumer-02/1.jpg",
    },
    {
        id: "consumer03",
        name: "consumer03",
        class: "consumer",
        coverPhoto: "/images/works/consumer-03/1.jpg",
    },
    {
        id: "development01",
        name: "development01",
        class: "development",
        coverPhoto: "/images/works/development-01/1.jpg",
    },
    {
        id: "development02",
        name: "development02",
        class: "development",
        coverPhoto: "/images/works/development-02/1.jpg",
    },
];

export const classes = [
    { title: "Office", id: "office" },
    { title: "Financial", id: "financial" },
    { title: "Hospitality", id: "hospitality" },
    { title: "Consumer", id: "consumer" },
    { title: "Health", id: "health" },
    { title: "Development", id: "development" },
    { title: "Church", id: "church" },
];

export interface work {
    id: string;
    name: string;
    class: string;
    fileRoot: string;
    photonum: number;
}

export const works: work[] = [
    {
        id: "church01",
        name: "church01",
        class: "church",
        fileRoot: "/images/works/church-01",
        photonum: 4,
    },
    {
        id: "consumer01",
        name: "consumer01",
        class: "consumer",
        fileRoot: "/images/works/consumer-01",
        photonum: 12,
    },
    {
        id: "consumer02",
        name: "consumer02",
        class: "consumer",
        fileRoot: "/images/works/consumer-02",
        photonum: 4,
    },
    {
        id: "consumer03",
        name: "consumer03",
        class: "consumer",
        fileRoot: "/images/works/consumer-03",
        photonum: 8,
    },
    {
        id: "development01",
        name: "development01",
        class: "development",
        fileRoot: "/images/works/development-01",
        photonum: 10,
    },
    {
        id: "development02",
        name: "development02",
        class: "development",
        fileRoot: "/images/works/development-02",
        photonum: 3,
    },
    {
        id: "development03",
        name: "development03",
        class: "development",
        fileRoot: "/images/works/development-03",
        photonum: 5,
    },
    {
        id: "financial01",
        name: "financial01",
        class: "financial",
        fileRoot: "/images/works/financial-01",
        photonum: 4,
    },
    {
        id: "financial02",
        name: "financial02",
        class: "financial",
        fileRoot: "/images/works/financial-02",
        photonum: 3,
    },
    {
        id: "health01",
        name: "health01",
        class: "health",
        fileRoot: "/images/works/health-01",
        photonum: 2,
    },
    {
        id: "hospitality01",
        name: "hospitality01",
        class: "hospitality",
        fileRoot: "/images/works/hospitality-01",
        photonum: 2,
    },
    {
        id: "hospitality02",
        name: "hospitality02",
        class: "hospitality",
        fileRoot: "/images/works/hospitality-02",
        photonum: 5,
    },
    {
        id: "office01",
        name: "office01",
        class: "office",
        fileRoot: "/images/works/office-01",
        photonum: 5,
    },
    {
        id: "office02",
        name: "office02",
        class: "office",
        fileRoot: "/images/works/office-02",
        photonum: 2,
    },
    {
        id: "office03",
        name: "office03",
        class: "office",
        fileRoot: "/images/works/office-03",
        photonum: 4,
    },
    {
        id: "office04",
        name: "office04",
        class: "office",
        fileRoot: "/images/works/office-04",
        photonum: 2,
    },
    {
        id: "office05",
        name: "office05",
        class: "office",
        fileRoot: "/images/works/office-05",
        photonum: 7,
    },
    {
        id: "office06",
        name: "office06",
        class: "office",
        fileRoot: "/images/works/office-06",
        photonum: 2,
    },
    {
        id: "office07",
        name: "office07",
        class: "office",
        fileRoot: "/images/works/office-07",
        photonum: 1,
    },
    {
        id: "office08",
        name: "office08",
        class: "office",
        fileRoot: "/images/works/office-08",
        photonum: 6,
    },
    {
        id: "office09",
        name: "office09",
        class: "office",
        fileRoot: "/images/works/office-09",
        photonum: 29,
    },
    {
        id: "office10",
        name: "office10",
        class: "office",
        fileRoot: "/images/works/office-10",
        photonum: 3,
    },
    {
        id: "office11",
        name: "office11",
        class: "office",
        fileRoot: "/images/works/office-11",
        photonum: 4,
    },
    {
        id: "office12",
        name: "office12",
        class: "office",
        fileRoot: "/images/works/office-12",
        photonum: 3,
    },
    {
        id: "office13",
        name: "office13",
        class: "office",
        fileRoot: "/images/works/office-13",
        photonum: 2,
    },
    {
        id: "office14",
        name: "office14",
        class: "office",
        fileRoot: "/images/works/office-14",
        photonum: 1,
    },
    {
        id: "office15",
        name: "office15",
        class: "office",
        fileRoot: "/images/works/office-15",
        photonum: 2,
    },
    {
        id: "residence01",
        name: "residence01",
        class: "residence",
        fileRoot: "/images/works/residence-01",
        photonum: 5,
    },
];
